version: '3.4'

services:
  db:
    image: erickbrunoro/challenge_db_development:latest
    build:
      context: ./db
      dockerfile: db.dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - back-end


  web:
    image: erickbrunoro/challenge_web_development:latest
    build:
      context: ${PWD}
      dockerfile: docker/dockerfile
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_CONFIG: ${FLASK_CONFIG}
      APPLICATION_DB: ${APPLICATION_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOSTNAME: "db"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: ["flask", "run", "--host", "::"]
    networks:
      - back-end
    volumes:
      - ${PWD}:/usr/src/app/code
    ports:
      - "5000:5000"
    depends_on:
      - db

networks:
  back-end:
    driver: bridge

volumes:
  pgdata: