version: '3.4'

services:
  db:
    image: postgres:${POSTGRES_VERSION}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      # LANG: ${POSTGRES_LANG}
      # LC_ALL: ${POSTGRES_LANG}
      # LC_CTYPE: ${POSTGRES_LANG}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data


  web:
    build:
      context: ${PWD}
      dockerfile: docker/dockerfile
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_CONFIG: ${FLASK_CONFIG}
      APPLICATION_DB: ${APPLICATION_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOSTNAME: "db"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: ["flask", "run", "--host", "::"]
    networks:
      - back-end
    volumes:
      - ${PWD}:/usr/src/app/code
    ports:
      - "5000:5000"
    depends_on:
      - db

networks:
  back-end:
    driver: bridge

volumes:
  pgdata: