version: '3.4'

services:
  db:
    build:
      context: ./db
      dockerfile: db.dockerfile
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - back-end


  web:
    build:
      context: ${PWD}
      dockerfile: docker/dockerfile.production
    environment:
      FLASK_APP: ${FLASK_APP}
      FLASK_ENV: ${FLASK_ENV}
      FLASK_CONFIG: ${FLASK_CONFIG}
      FLASK_SECRET_KEY: ${FLASK_SECRET_KEY}
      APPLICATION_DB: ${APPLICATION_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_HOSTNAME: "db"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_PORT: ${POSTGRES_PORT}
    command: ["gunicorn", "-w", "4", "-b", "[::]:${SERVER_PORT}", "application.wsgi:app"]
    volumes:
      - ${PWD}:/usr/src/app/code
    ports:
      - "${PORT}:${SERVER_PORT}"
    networks:
      - back-end

networks:
  back-end:
    driver: bridge

volumes:
  pgdata: