"""empty message

Revision ID: 1c1dea1db0c2
Revises: 
Create Date: 2022-04-27 22:59:35.932539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c1dea1db0c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('file_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transaction', 'transactions_file', ['file_id'], ['id'])
    op.add_column('transactions_file', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions_file', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions_file', type_='foreignkey')
    op.drop_column('transactions_file', 'user_id')
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'file_id')
    # ### end Alembic commands ###
