"""empty message

Revision ID: 8d758d1555ee
Revises: 
Create Date: 2022-04-20 16:31:08.757200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d758d1555ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('login_id', sa.Integer(), sa.Identity(always=False, start=5000, increment=1), nullable=False))
    op.add_column('user', sa.Column('active', sa.Boolean(), sa.ColumnDefault(True), nullable=True))
    op.execute('UPDATE "user" SET active = true')
    op.alter_column('user', 'active', nullable=False)
    op.create_unique_constraint(None, 'user', ['login_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'active')
    op.drop_column('user', 'login_id')
    # ### end Alembic commands ###
